### ISSUE TITLE
Not exactly an issue but what makes python requires >=3.8 <4.0

### ISSUE THREAD

**Issue by ZBarthelemy** [vduseev/opensearch-logger#1]
What is limiting to support a distrib for older version of python ? Say 3.6

**Comment by vduseev** [comment]
Hi @ZBarthelemy, apologies for the late answer.

I don't think there is much sense adding Python 3.6 support as it has reached its end of life and Python 3.7 is due for the same in 11 months. It shouldn't be a trouble though to add both. Let me check if I can do that.

**Comment by vduseev** [comment]
Thank you @ZBarthelemy for your suggestion 👏 All tests worked fine on Python 3.6. I've published a new version to PyPI.

**Comment by ZBarthelemy** [comment]
Thanks mate! I agree on the end of life comment, but unfortunately running a pretty old stack at work :(
