### ISSUE TITLE
The logger is logging "status response" from Elastic / OpenSearch

### ISSUE THREAD

**Issue by projx** [vduseev/opensearch-logger#3]
Hi

I'm doing some testing this with this and discovered w that the response from the Search server is being logged itself:

`
 {
  "_index": "test1",
  "_type": "_doc",
  "_id": "1QPANVVKTN6",
  "_score": 2,
  "@timestamp": "2022-08-02T15:42:25.449999872Z",
  "_source": {
    "agent.ephemeral_id": "c7629bf6-b7db-406e-a065-188f66f96d38",
    "agent.type": "opensearch-logger",
    "agent.version": "1.2.1",
    "args": [
      "POST",
      "http://127.0.0.1:4080/api/_bulk",
      "200",
      "0.004238128662109375"
    ],
    "ecs.version": "1.4.0",
    "host.hostname": "mba.local",
    "host.id": "mba.local",
    "host.ip": "10.10.50.200",
    "host.name": "mba.local",
    "log.level": "INFO",
    "log.logger": "opensearch",
    "log.origin.file.line": 235,
    "log.origin.file.name": "base.py",
    "log.origin.file.path": "/Users/kelvin/Prog/virtualenvs/qtool/lib/python3.9/site-packages/opensearchpy/connection/base.py",
    "log.origin.function": "log_request_success",
    "log.origin.module": "base",
    "log.original": "POST http://127.0.0.1:4080/api/_bulk [status:200 request:0.004s]",
    "log.process.name": "MainProcess",
    "log.process.pid": 36416,
    "log.thread.id": 4298327424,
    "log.thread.name": "MainThread",
    "message": "POST http://127.0.0.1:4080/api/_bulk [status:200 request:0.004s]",
    "stack_info": ""
  }
}
`              
If you see the Message, you'll see this is the status return from Elastic and Open Search.

    "message": "POST http://127.0.0.1:4080/api/_bulk [status:200 request:0.004s]",

**Comment by projx** [comment]
Awesome thank you - you showed me the problem, I was not passing a name when calling logging.getLogger()... I added that and the problem went away.

**Comment by vduseev** [comment]
Great! Glad to hear that 👏
